#!/usr/bin/env bash
# Render completions/agent-kit.bash from a completion-spec JSON file.
#
# Usage:
#   scripts/completions/render-bash.sh SPEC_FILE > completions/agent-kit.bash
#
# Requires: jq
set -euo pipefail

spec="$1"

top_level="$(jq -r '.commands[].name' "$spec" | LC_ALL=C sort -u | tr '\n' ' ')"
top_level="${top_level% }"

cat <<EOF
# agent-kit shell completion (bash) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

_agent_kit_completion()
{
    local current command
    current="\${COMP_WORDS[COMP_CWORD]}"
    command="\${COMP_WORDS[1]-}"
    COMPREPLY=()

    if ((COMP_CWORD == 1)); then
        mapfile -t COMPREPLY < <(compgen -W "$top_level" -- "\$current")
        return
    fi

    case "\$command" in
EOF

jq -r '.commands[].name' "$spec" | LC_ALL=C sort -u | while IFS= read -r name; do
    mode_count="$(jq -r --arg n "$name" '[.commands[] | select(.name==$n) | .modes[]?] | length' "$spec")"
    modes="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .modes[]?' "$spec" | LC_ALL=C sort -u | tr '\n' ' ')"
    modes="${modes% }"
    flags="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .flags[]? | split(" | ")[]' "$spec" | LC_ALL=C sort -u | tr '\n' ' ')"
    flags="${flags% } --help --introspect"

    printf '        %s)\n' "$name"
    if ((mode_count > 0)); then
        printf '            if ((COMP_CWORD == 2)); then\n'
        printf '                mapfile -t COMPREPLY < <(compgen -W "%s" -- "$current")\n' "$modes"
        printf '            else\n'
        printf '                mapfile -t COMPREPLY < <(compgen -W "%s" -- "$current")\n' "$flags"
        printf '            fi\n'
    else
        printf '            mapfile -t COMPREPLY < <(compgen -W "%s" -- "$current")\n' "$flags"
    fi
    printf '            ;;\n\n'
done

cat <<'EOF'
    esac
}

complete -o bashdefault -o default -F _agent_kit_completion agent-kit ak
EOF
