#!/usr/bin/env bash
# Render completions/agent-kit.fish from a completion-spec JSON file.
#
# Usage:
#   scripts/completions/render-fish.sh SPEC_FILE > completions/agent-kit.fish
#
# Requires: jq
set -euo pipefail

spec="$1"

# fish -d descriptions are single-quoted; strip apostrophes rather than
# escape them (a one-line generated hint doesn't need exact prose fidelity).
sanitize() {
    tr -d "'"
}

cat <<'EOF'
# agent-kit shell completion (fish) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

complete -c agent-kit -e
complete -c ak -e

function __agent_kit_needs_command
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 1
end

function __agent_kit_command_is
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2
    and test "$tokens[2]" = "$argv[1]"
end

function __agent_kit_needs_mode
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 2
    and test "$tokens[2]" = "$argv[1]"
end

EOF

jq -r '.commands[] | [.name, ((.description // "") | gsub("\n"; " "))] | @tsv' "$spec" | LC_ALL=C sort -u | while IFS=$'\t' read -r name desc; do
    desc="$(printf '%s' "$desc" | sanitize)"
    for prog in agent-kit ak; do
        printf "complete -c %s -n __agent_kit_needs_command -a '%s' -d '%s'\n" "$prog" "$name" "$desc"
    done
done
printf '\n'

first=1
jq -r '.commands[].name' "$spec" | LC_ALL=C sort -u | while IFS= read -r name; do
    block=""

    mode_count="$(jq -r --arg n "$name" '[.commands[] | select(.name==$n) | .modes[]?] | length' "$spec")"
    if ((mode_count > 0)); then
        modes="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .modes[]?' "$spec" | LC_ALL=C sort -u | tr '\n' ' ')"
        modes="${modes% }"
        for prog in agent-kit ak; do
            block+="$(printf "complete -c %s -n '__agent_kit_needs_mode %s' -a '%s'\n" "$prog" "$name" "$modes")"$'\n'
        done
    fi

    while IFS= read -r flag; do
        [[ -n "$flag" ]] || continue
        case "$flag" in
            --*) opt="-l ${flag#--}" ;;
            -?) opt="-s ${flag#-}" ;;
            *) continue ;;
        esac
        for prog in agent-kit ak; do
            block+="$(printf "complete -c %s -n '__agent_kit_command_is %s' %s\n" "$prog" "$name" "$opt")"$'\n'
        done
    done < <(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .flags[]? | split(" | ")[]' "$spec" | LC_ALL=C sort -u)

    [[ -n "$block" ]] || continue
    ((first)) || printf '\n'
    first=0
    printf '%s' "$block"
done
