#!/usr/bin/env bash
# Render completions/restsift.fish from a completion-spec JSON file.
#
# Usage:
#   scripts/completions/render-fish.sh SPEC_FILE > completions/restsift.fish
#
# Requires: jq
set -euo pipefail

spec="$1"

# fish -d descriptions are single-quoted; strip apostrophes rather than
# escape them (a one-line generated hint doesn't need exact prose fidelity).
sanitize() {
    tr -d "'"
}

cat <<'EOF'
# restsift shell completion (fish) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

complete -c restsift -e
complete -c res -e
complete -c agent-kit -e
complete -c ak -e

function __restsift_needs_command
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 1
end

function __restsift_command_is
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2
    and test "$tokens[2]" = "$argv[1]"
end

function __restsift_needs_mode
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 2
    and test "$tokens[2]" = "$argv[1]"
end

EOF

jq -r '.commands[] | [.name, ((.description // "") | gsub("\n"; " "))] | @tsv' "$spec" | LC_ALL=C sort -u | while IFS=$'\t' read -r name desc; do
    desc="$(printf '%s' "$desc" | sanitize)"
    for prog in restsift res agent-kit ak; do
        printf "complete -c %s -n __restsift_needs_command -a '%s' -d '%s'\n" "$prog" "$name" "$desc"
    done
done

# Aliases (e.g. "rb" for "rollback") get their own top-level candidate,
# distinguished from the canonical name by description only.
jq -r '.commands[] | .name as $n | .aliases[]? | [., $n] | @tsv' "$spec" | LC_ALL=C sort -u | while IFS=$'\t' read -r alias name; do
    for prog in restsift res agent-kit ak; do
        printf "complete -c %s -n __restsift_needs_command -a '%s' -d 'alias for %s'\n" "$prog" "$alias" "$name"
    done
done
printf '\n'

first=1
jq -r '.commands[].name' "$spec" | LC_ALL=C sort -u | while IFS= read -r name; do
    block=""

    # __restsift_command_is/__restsift_needs_mode compare a single literal
    # token, so the mode/flag block below must be repeated once per label
    # (the canonical name AND each short alias, e.g. "rollback" and "rb") for
    # `ak rb <TAB>` to complete identically to `ak rollback <TAB>`.
    labels="$name"
    while IFS= read -r alias; do
        [[ -n "$alias" ]] && labels+=$'\n'"$alias"
    done < <(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .aliases[]?' "$spec")

    mode_count="$(jq -r --arg n "$name" '[.commands[] | select(.name==$n) | .modes[]?] | length' "$spec")"
    modes=""
    if ((mode_count > 0)); then
        modes="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .modes[]?' "$spec" | LC_ALL=C sort -u | tr '\n' ' ')"
        modes="${modes% }"
    fi

    flags_list="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .flags[]? | split(" | ")[]' "$spec" | LC_ALL=C sort -u)"

    while IFS= read -r label; do
        [[ -n "$label" ]] || continue

        if [[ -n "$modes" ]]; then
            for prog in restsift res agent-kit ak; do
                block+="$(printf "complete -c %s -n '__restsift_needs_mode %s' -a '%s'\n" "$prog" "$label" "$modes")"$'\n'
            done
        fi

        while IFS= read -r flag; do
            [[ -n "$flag" ]] || continue
            case "$flag" in
                --*) opt="-l ${flag#--}" ;;
                -?) opt="-s ${flag#-}" ;;
                *) continue ;;
            esac
            for prog in restsift res agent-kit ak; do
                block+="$(printf "complete -c %s -n '__restsift_command_is %s' %s\n" "$prog" "$label" "$opt")"$'\n'
            done
        done <<<"$flags_list"
    done <<<"$labels"

    [[ -n "$block" ]] || continue
    ((first)) || printf '\n'
    first=0
    printf '%s' "$block"
done
