#!/usr/bin/env bash
# Render completions/_agent-kit (zsh) from a completion-spec JSON file.
#
# Usage:
#   scripts/completions/render-zsh.sh SPEC_FILE > completions/_agent-kit
#
# Requires: jq
set -euo pipefail

spec="$1"

# zsh's `_describe` splits each array element on the FIRST `:`, so a literal
# `:` or `'` inside a description would corrupt the spec; strip both rather
# than escape them (generated descriptions are a one-line hint, not prose).
sanitize() {
    tr -d ":'"
}

cat <<'EOF'
#compdef agent-kit ak
# agent-kit shell completion (zsh) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

_agent_kit()
{
    local context state line
    typeset -A opt_args

    local -a commands
    commands=(
EOF

jq -r '.commands[] | [.name, ((.description // "") | gsub("\n"; " "))] | @tsv' "$spec" | LC_ALL=C sort -u | while IFS=$'\t' read -r name desc; do
    desc="$(printf '%s' "$desc" | sanitize)"
    printf "        '%s:%s'\n" "$name" "$desc"
done

cat <<'EOF'
    )

    _arguments -C \
        '1:command:->command' \
        '*::argument:->arguments'

    case "$state" in
        command)
            _describe 'agent-kit command' commands
            ;;

        arguments)
            case "$line[1]" in
EOF

jq -r '.commands[].name' "$spec" | LC_ALL=C sort -u | while IFS= read -r name; do
    mode_count="$(jq -r --arg n "$name" '[.commands[] | select(.name==$n) | .modes[]?] | length' "$spec")"
    flags="$(jq -r --arg n "$name" '.commands[] | select(.name==$n) | .flags[]? | split(" | ")[]' "$spec" | LC_ALL=C sort -u)"
    flags="$(printf '%s\n--help\n--introspect\n' "$flags" | LC_ALL=C sort -u)"

    printf '                %s)\n' "$name"
    if ((mode_count > 0)); then
        printf '                    local -a modes\n'
        printf '                    modes=(\n'
        jq -r --arg n "$name" '.commands[] | select(.name==$n) | .modes[]?' "$spec" | LC_ALL=C sort -u | while IFS= read -r mode; do
            printf "                        '%s'\n" "$mode"
        done
        printf '                    )\n'
        printf '                    if ((CURRENT == 2)); then\n'
        printf "                        _describe '%s mode' modes\n" "$name"
        printf '                    else\n'
        printf '                        _arguments \\\n'
        printf '%s' "$flags" | while IFS= read -r flag; do
            [[ -n "$flag" ]] || continue
            printf "                            '%s' \\\\\n" "$flag"
        done
        printf "                            '*:path:_files'\n"
        printf '                    fi\n'
    else
        printf '                    _arguments \\\n'
        printf '%s' "$flags" | while IFS= read -r flag; do
            [[ -n "$flag" ]] || continue
            printf "                        '%s' \\\\\n" "$flag"
        done
        printf "                        '*:path:_files'\n"
    fi
    printf '                    ;;\n\n'
done

cat <<'EOF'
            esac
            ;;
    esac
}

compdef _agent_kit agent-kit ak
EOF
