# agent-kit shell completion (fish) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

complete -c agent-kit -e
complete -c ak -e

function __agent_kit_needs_command
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 1
end

function __agent_kit_command_is
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2
    and test "$tokens[2]" = "$argv[1]"
end

function __agent_kit_needs_mode
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 2
    and test "$tokens[2]" = "$argv[1]"
end

complete -c agent-kit -n __agent_kit_needs_command -a 'all-f-into-one' -d 'all-f-into-one.sh (formerly all_in_one.sh / combine_files.sh) Recursively collects filenames and contents, writes them to a single output file at project root. Prunes ignored directories (entire subtrees) and excludes selected files. Each file block (header + content + footer) is wrapped inside triple backticks.'
complete -c ak -n __agent_kit_needs_command -a 'all-f-into-one' -d 'all-f-into-one.sh (formerly all_in_one.sh / combine_files.sh) Recursively collects filenames and contents, writes them to a single output file at project root. Prunes ignored directories (entire subtrees) and excludes selected files. Each file block (header + content + footer) is wrapped inside triple backticks.'
complete -c agent-kit -n __agent_kit_needs_command -a 'completion' -d 'Print a generated shell-completion definition for agent-kit (and its short alias `ak`) to stdout. Non-mutating: it only prints a file, it never touches shell configuration or installs anything.'
complete -c ak -n __agent_kit_needs_command -a 'completion' -d 'Print a generated shell-completion definition for agent-kit (and its short alias `ak`) to stdout. Non-mutating: it only prints a file, it never touches shell configuration or installs anything.'
complete -c agent-kit -n __agent_kit_needs_command -a 'context' -d 'ai-context — canonical context-building command group (thin loader).'
complete -c ak -n __agent_kit_needs_command -a 'context' -d 'ai-context — canonical context-building command group (thin loader).'
complete -c agent-kit -n __agent_kit_needs_command -a 'doctor' -d 'Report agent-kit installation and environment health for bug triage.'
complete -c ak -n __agent_kit_needs_command -a 'doctor' -d 'Report agent-kit installation and environment health for bug triage.'
complete -c agent-kit -n __agent_kit_needs_command -a 'edit' -d 'Guarded edit wrapper for broad repository modifications (thin loader).'
complete -c ak -n __agent_kit_needs_command -a 'edit' -d 'Guarded edit wrapper for broad repository modifications (thin loader).'
complete -c agent-kit -n __agent_kit_needs_command -a 'fd-files' -d 'Repo-aware file discovery wrapper.'
complete -c ak -n __agent_kit_needs_command -a 'fd-files' -d 'Repo-aware file discovery wrapper.'
complete -c agent-kit -n __agent_kit_needs_command -a 'file-freshness' -d 'Show which docs/config files have uncommitted changes (git status of key paths).'
complete -c ak -n __agent_kit_needs_command -a 'file-freshness' -d 'Show which docs/config files have uncommitted changes (git status of key paths).'
complete -c agent-kit -n __agent_kit_needs_command -a 'git' -d 'ai-git — canonical git-inspection command group (thin loader).'
complete -c ak -n __agent_kit_needs_command -a 'git' -d 'ai-git — canonical git-inspection command group (thin loader).'
complete -c agent-kit -n __agent_kit_needs_command -a 'inspect' -d 'Canonical read-only inspection command group (thin router).'
complete -c ak -n __agent_kit_needs_command -a 'inspect' -d 'Canonical read-only inspection command group (thin router).'
complete -c agent-kit -n __agent_kit_needs_command -a 'preview-file' -d 'preview-file.sh — safely preview a slice of a text file with guardrails (size/byte gate, binary + .git blocking, column truncation).'
complete -c ak -n __agent_kit_needs_command -a 'preview-file' -d 'preview-file.sh — safely preview a slice of a text file with guardrails (size/byte gate, binary + .git blocking, column truncation).'
complete -c agent-kit -n __agent_kit_needs_command -a 'refactor-scan' -d 'Flag refactor candidates: rank files by scc complexity and functions by lizard NLOC.'
complete -c ak -n __agent_kit_needs_command -a 'refactor-scan' -d 'Flag refactor candidates: rank files by scc complexity and functions by lizard NLOC.'
complete -c agent-kit -n __agent_kit_needs_command -a 'repo' -d 'Canonical repository-metadata command group (thin router).'
complete -c ak -n __agent_kit_needs_command -a 'repo' -d 'Canonical repository-metadata command group (thin router).'
complete -c agent-kit -n __agent_kit_needs_command -a 'repo-stats' -d 'Count the files Git currently tracks in this repository.'
complete -c ak -n __agent_kit_needs_command -a 'repo-stats' -d 'Count the files Git currently tracks in this repository.'
complete -c agent-kit -n __agent_kit_needs_command -a 'repo-tool-inventory' -d 'List every toolkit command with its one-line summary (a discoverable map).'
complete -c ak -n __agent_kit_needs_command -a 'repo-tool-inventory' -d 'List every toolkit command with its one-line summary (a discoverable map).'
complete -c agent-kit -n __agent_kit_needs_command -a 'rg-code' -d 'Production-grade code search wrapper with repo-aware defaults.'
complete -c ak -n __agent_kit_needs_command -a 'rg-code' -d 'Production-grade code search wrapper with repo-aware defaults.'
complete -c agent-kit -n __agent_kit_needs_command -a 'rollback' -d 'Review and apply repository-local rollback snapshots created by AI tooling sessions.'
complete -c ak -n __agent_kit_needs_command -a 'rollback' -d 'Review and apply repository-local rollback snapshots created by AI tooling sessions.'
complete -c agent-kit -n __agent_kit_needs_command -a 's' -d 'Short repository search: default to text mode and auto-detect the search root.'
complete -c ak -n __agent_kit_needs_command -a 's' -d 'Short repository search: default to text mode and auto-detect the search root.'
complete -c agent-kit -n __agent_kit_needs_command -a 'search' -d 'ai-search.sh — unified repository search entrypoint (thin facade).'
complete -c ak -n __agent_kit_needs_command -a 'search' -d 'ai-search.sh — unified repository search entrypoint (thin facade).'
complete -c agent-kit -n __agent_kit_needs_command -a 'search-introspect' -d 'ai-search-introspect.sh — print 100% of the modes, flags, env vars, and per-mode argument contracts that ai-search.sh and ai-search-multi.sh accept.'
complete -c ak -n __agent_kit_needs_command -a 'search-introspect' -d 'ai-search-introspect.sh — print 100% of the modes, flags, env vars, and per-mode argument contracts that ai-search.sh and ai-search-multi.sh accept.'
complete -c agent-kit -n __agent_kit_needs_command -a 'search-multi' -d 'Batch wrapper around ai-search.sh: run one safe search MODE against several queries in a single approved invocation.'
complete -c ak -n __agent_kit_needs_command -a 'search-multi' -d 'Batch wrapper around ai-search.sh: run one safe search MODE against several queries in a single approved invocation.'
complete -c agent-kit -n __agent_kit_needs_command -a 'session' -d 'Canonical agent-session command group (thin router).'
complete -c ak -n __agent_kit_needs_command -a 'session' -d 'Canonical agent-session command group (thin router).'
complete -c agent-kit -n __agent_kit_needs_command -a 'session-checkpoint' -d 'Create a repository-local checkpoint using the shared snapshot system.'
complete -c ak -n __agent_kit_needs_command -a 'session-checkpoint' -d 'Create a repository-local checkpoint using the shared snapshot system.'
complete -c agent-kit -n __agent_kit_needs_command -a 'structured' -d 'Structured data query wrapper for AI agents.'
complete -c ak -n __agent_kit_needs_command -a 'structured' -d 'Structured data query wrapper for AI agents.'
complete -c agent-kit -n __agent_kit_needs_command -a 'task' -d 'Project task discovery wrapper for AI agents.'
complete -c ak -n __agent_kit_needs_command -a 'task' -d 'Project task discovery wrapper for AI agents.'
complete -c agent-kit -n __agent_kit_needs_command -a 'test' -d 'ai-test — canonical test-selection/execution command group (thin loader).'
complete -c ak -n __agent_kit_needs_command -a 'test' -d 'ai-test — canonical test-selection/execution command group (thin loader).'
complete -c agent-kit -n __agent_kit_needs_command -a 'verify' -d 'Project-aware verification gate for AI-driven changes (thin loader).'
complete -c ak -n __agent_kit_needs_command -a 'verify' -d 'Project-aware verification gate for AI-driven changes (thin loader).'
complete -c agent-kit -n __agent_kit_needs_command -a 'watch-loop' -d 'Re-run a command automatically whenever watched files change (blocks until Ctrl-C).'
complete -c ak -n __agent_kit_needs_command -a 'watch-loop' -d 'Re-run a command automatically whenever watched files change (blocks until Ctrl-C).'

complete -c agent-kit -n '__agent_kit_needs_mode completion' -a 'auto bash fish zsh'
complete -c ak -n '__agent_kit_needs_mode completion' -a 'auto bash fish zsh'

complete -c agent-kit -n '__agent_kit_needs_mode context' -a 'diff ensure estimate file generate pack status tree'
complete -c ak -n '__agent_kit_needs_mode context' -a 'diff ensure estimate file generate pack status tree'
complete -c agent-kit -n '__agent_kit_command_is context' -l compress
complete -c ak -n '__agent_kit_command_is context' -l compress
complete -c agent-kit -n '__agent_kit_command_is context' -l help
complete -c ak -n '__agent_kit_command_is context' -l help
complete -c agent-kit -n '__agent_kit_command_is context' -l multiplier
complete -c ak -n '__agent_kit_command_is context' -l multiplier
complete -c agent-kit -n '__agent_kit_command_is context' -l multiplier-label
complete -c ak -n '__agent_kit_command_is context' -l multiplier-label
complete -c agent-kit -n '__agent_kit_command_is context' -l no-compress
complete -c ak -n '__agent_kit_command_is context' -l no-compress
complete -c agent-kit -n '__agent_kit_command_is context' -l no-regen
complete -c ak -n '__agent_kit_command_is context' -l no-regen
complete -c agent-kit -n '__agent_kit_command_is context' -l output
complete -c ak -n '__agent_kit_command_is context' -l output
complete -c agent-kit -n '__agent_kit_command_is context' -l regen
complete -c ak -n '__agent_kit_command_is context' -l regen
complete -c agent-kit -n '__agent_kit_command_is context' -l reserved-output
complete -c ak -n '__agent_kit_command_is context' -l reserved-output
complete -c agent-kit -n '__agent_kit_command_is context' -l style
complete -c ak -n '__agent_kit_command_is context' -l style
complete -c agent-kit -n '__agent_kit_command_is context' -s h
complete -c ak -n '__agent_kit_command_is context' -s h

complete -c agent-kit -n '__agent_kit_needs_mode edit' -a 'apply ast-grep comby patch rollback sd'
complete -c ak -n '__agent_kit_needs_mode edit' -a 'apply ast-grep comby patch rollback sd'
complete -c agent-kit -n '__agent_kit_command_is edit' -l allow-dirty-tree
complete -c ak -n '__agent_kit_command_is edit' -l allow-dirty-tree
complete -c agent-kit -n '__agent_kit_command_is edit' -l apply
complete -c ak -n '__agent_kit_command_is edit' -l apply
complete -c agent-kit -n '__agent_kit_command_is edit' -l dry-run
complete -c ak -n '__agent_kit_command_is edit' -l dry-run
complete -c agent-kit -n '__agent_kit_command_is edit' -l exclude
complete -c ak -n '__agent_kit_command_is edit' -l exclude
complete -c agent-kit -n '__agent_kit_command_is edit' -l format
complete -c ak -n '__agent_kit_command_is edit' -l format
complete -c agent-kit -n '__agent_kit_command_is edit' -l glob
complete -c ak -n '__agent_kit_command_is edit' -l glob
complete -c agent-kit -n '__agent_kit_command_is edit' -l help
complete -c ak -n '__agent_kit_command_is edit' -l help
complete -c agent-kit -n '__agent_kit_command_is edit' -l max-bytes
complete -c ak -n '__agent_kit_command_is edit' -l max-bytes
complete -c agent-kit -n '__agent_kit_command_is edit' -l max-files
complete -c ak -n '__agent_kit_command_is edit' -l max-files
complete -c agent-kit -n '__agent_kit_command_is edit' -l max-replacements
complete -c ak -n '__agent_kit_command_is edit' -l max-replacements
complete -c agent-kit -n '__agent_kit_command_is edit' -l no-verify
complete -c ak -n '__agent_kit_command_is edit' -l no-verify
complete -c agent-kit -n '__agent_kit_command_is edit' -l require-clean-tree
complete -c ak -n '__agent_kit_command_is edit' -l require-clean-tree
complete -c agent-kit -n '__agent_kit_command_is edit' -l verify
complete -c ak -n '__agent_kit_command_is edit' -l verify
complete -c agent-kit -n '__agent_kit_command_is edit' -s h
complete -c ak -n '__agent_kit_command_is edit' -s h

complete -c agent-kit -n '__agent_kit_command_is fd-files' -l help
complete -c ak -n '__agent_kit_command_is fd-files' -l help
complete -c agent-kit -n '__agent_kit_command_is fd-files' -l hidden
complete -c ak -n '__agent_kit_command_is fd-files' -l hidden
complete -c agent-kit -n '__agent_kit_command_is fd-files' -l json
complete -c ak -n '__agent_kit_command_is fd-files' -l json
complete -c agent-kit -n '__agent_kit_command_is fd-files' -l type
complete -c ak -n '__agent_kit_command_is fd-files' -l type
complete -c agent-kit -n '__agent_kit_command_is fd-files' -s h
complete -c ak -n '__agent_kit_command_is fd-files' -s h

complete -c agent-kit -n '__agent_kit_needs_mode git' -a 'blame history origin pr-context'
complete -c ak -n '__agent_kit_needs_mode git' -a 'blame history origin pr-context'
complete -c agent-kit -n '__agent_kit_command_is git' -l checks
complete -c ak -n '__agent_kit_command_is git' -l checks
complete -c agent-kit -n '__agent_kit_command_is git' -l diff
complete -c ak -n '__agent_kit_command_is git' -l diff
complete -c agent-kit -n '__agent_kit_command_is git' -l field
complete -c ak -n '__agent_kit_command_is git' -l field
complete -c agent-kit -n '__agent_kit_command_is git' -l help
complete -c ak -n '__agent_kit_command_is git' -l help
complete -c agent-kit -n '__agent_kit_command_is git' -l json
complete -c ak -n '__agent_kit_command_is git' -l json
complete -c agent-kit -n '__agent_kit_command_is git' -l pack
complete -c ak -n '__agent_kit_command_is git' -l pack
complete -c agent-kit -n '__agent_kit_command_is git' -l reviews
complete -c ak -n '__agent_kit_command_is git' -l reviews
complete -c agent-kit -n '__agent_kit_command_is git' -s h
complete -c ak -n '__agent_kit_command_is git' -s h

complete -c agent-kit -n '__agent_kit_needs_mode inspect' -a 'data file shell'
complete -c ak -n '__agent_kit_needs_mode inspect' -a 'data file shell'

complete -c agent-kit -n '__agent_kit_command_is preview-file' -l around
complete -c ak -n '__agent_kit_command_is preview-file' -l around
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l context
complete -c ak -n '__agent_kit_command_is preview-file' -l context
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l dry-run
complete -c ak -n '__agent_kit_command_is preview-file' -l dry-run
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l force
complete -c ak -n '__agent_kit_command_is preview-file' -l force
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l help
complete -c ak -n '__agent_kit_command_is preview-file' -l help
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l lines
complete -c ak -n '__agent_kit_command_is preview-file' -l lines
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l max-bytes
complete -c ak -n '__agent_kit_command_is preview-file' -l max-bytes
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l max-columns
complete -c ak -n '__agent_kit_command_is preview-file' -l max-columns
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l plain
complete -c ak -n '__agent_kit_command_is preview-file' -l plain
complete -c agent-kit -n '__agent_kit_command_is preview-file' -l range
complete -c ak -n '__agent_kit_command_is preview-file' -l range
complete -c agent-kit -n '__agent_kit_command_is preview-file' -s h
complete -c ak -n '__agent_kit_command_is preview-file' -s h

complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l ccn-threshold
complete -c ak -n '__agent_kit_command_is refactor-scan' -l ccn-threshold
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l complexity-threshold
complete -c ak -n '__agent_kit_command_is refactor-scan' -l complexity-threshold
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l exclude-dir
complete -c ak -n '__agent_kit_command_is refactor-scan' -l exclude-dir
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l ext
complete -c ak -n '__agent_kit_command_is refactor-scan' -l ext
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l fail-on-findings
complete -c ak -n '__agent_kit_command_is refactor-scan' -l fail-on-findings
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l folder
complete -c ak -n '__agent_kit_command_is refactor-scan' -l folder
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l help
complete -c ak -n '__agent_kit_command_is refactor-scan' -l help
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l human
complete -c ak -n '__agent_kit_command_is refactor-scan' -l human
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l lang
complete -c ak -n '__agent_kit_command_is refactor-scan' -l lang
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l nloc-threshold
complete -c ak -n '__agent_kit_command_is refactor-scan' -l nloc-threshold
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l no-parallel
complete -c ak -n '__agent_kit_command_is refactor-scan' -l no-parallel
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l no-report
complete -c ak -n '__agent_kit_command_is refactor-scan' -l no-report
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l output-dir
complete -c ak -n '__agent_kit_command_is refactor-scan' -l output-dir
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l param-threshold
complete -c ak -n '__agent_kit_command_is refactor-scan' -l param-threshold
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l quiet
complete -c ak -n '__agent_kit_command_is refactor-scan' -l quiet
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -l scc-format
complete -c ak -n '__agent_kit_command_is refactor-scan' -l scc-format
complete -c agent-kit -n '__agent_kit_command_is refactor-scan' -s h
complete -c ak -n '__agent_kit_command_is refactor-scan' -s h

complete -c agent-kit -n '__agent_kit_needs_mode repo' -a 'stats status tasks tools'
complete -c ak -n '__agent_kit_needs_mode repo' -a 'stats status tasks tools'

complete -c agent-kit -n '__agent_kit_command_is rg-code' -l context
complete -c ak -n '__agent_kit_command_is rg-code' -l context
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l count
complete -c ak -n '__agent_kit_command_is rg-code' -l count
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l files
complete -c ak -n '__agent_kit_command_is rg-code' -l files
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l help
complete -c ak -n '__agent_kit_command_is rg-code' -l help
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l ignore-case
complete -c ak -n '__agent_kit_command_is rg-code' -l ignore-case
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l json
complete -c ak -n '__agent_kit_command_is rg-code' -l json
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l mode
complete -c ak -n '__agent_kit_command_is rg-code' -l mode
complete -c agent-kit -n '__agent_kit_command_is rg-code' -l type
complete -c ak -n '__agent_kit_command_is rg-code' -l type
complete -c agent-kit -n '__agent_kit_command_is rg-code' -s C
complete -c ak -n '__agent_kit_command_is rg-code' -s C
complete -c agent-kit -n '__agent_kit_command_is rg-code' -s h
complete -c ak -n '__agent_kit_command_is rg-code' -s h
complete -c agent-kit -n '__agent_kit_command_is rg-code' -s i
complete -c ak -n '__agent_kit_command_is rg-code' -s i

complete -c agent-kit -n '__agent_kit_needs_mode rollback' -a 'apply list prune show'
complete -c ak -n '__agent_kit_needs_mode rollback' -a 'apply list prune show'
complete -c agent-kit -n '__agent_kit_command_is rollback' -l days
complete -c ak -n '__agent_kit_command_is rollback' -l days
complete -c agent-kit -n '__agent_kit_command_is rollback' -l help
complete -c ak -n '__agent_kit_command_is rollback' -l help
complete -c agent-kit -n '__agent_kit_command_is rollback' -s h
complete -c ak -n '__agent_kit_command_is rollback' -s h

complete -c agent-kit -n '__agent_kit_command_is s' -l changed
complete -c ak -n '__agent_kit_command_is s' -l changed
complete -c agent-kit -n '__agent_kit_command_is s' -l config
complete -c ak -n '__agent_kit_command_is s' -l config
complete -c agent-kit -n '__agent_kit_command_is s' -l deps
complete -c ak -n '__agent_kit_command_is s' -l deps
complete -c agent-kit -n '__agent_kit_command_is s' -l diff
complete -c ak -n '__agent_kit_command_is s' -l diff
complete -c agent-kit -n '__agent_kit_command_is s' -l docs
complete -c ak -n '__agent_kit_command_is s' -l docs
complete -c agent-kit -n '__agent_kit_command_is s' -l history
complete -c ak -n '__agent_kit_command_is s' -l history
complete -c agent-kit -n '__agent_kit_command_is s' -l staged
complete -c ak -n '__agent_kit_command_is s' -l staged
complete -c agent-kit -n '__agent_kit_command_is s' -l tests
complete -c ak -n '__agent_kit_command_is s' -l tests
complete -c agent-kit -n '__agent_kit_command_is s' -l tracked
complete -c ak -n '__agent_kit_command_is s' -l tracked

complete -c agent-kit -n '__agent_kit_needs_mode search' -a 'batch capabilities changed-files changed-text class config config-key deps diff docs doctor enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns'
complete -c ak -n '__agent_kit_needs_mode search' -a 'batch capabilities changed-files changed-text class config config-key deps diff docs doctor enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns'
complete -c agent-kit -n '__agent_kit_command_is search' -l absolute
complete -c ak -n '__agent_kit_command_is search' -l absolute
complete -c agent-kit -n '__agent_kit_command_is search' -l after-context
complete -c ak -n '__agent_kit_command_is search' -l after-context
complete -c agent-kit -n '__agent_kit_command_is search' -l base
complete -c ak -n '__agent_kit_command_is search' -l base
complete -c agent-kit -n '__agent_kit_command_is search' -l before-context
complete -c ak -n '__agent_kit_command_is search' -l before-context
complete -c agent-kit -n '__agent_kit_command_is search' -l case-sensitive
complete -c ak -n '__agent_kit_command_is search' -l case-sensitive
complete -c agent-kit -n '__agent_kit_command_is search' -l context
complete -c ak -n '__agent_kit_command_is search' -l context
complete -c agent-kit -n '__agent_kit_command_is search' -l count
complete -c ak -n '__agent_kit_command_is search' -l count
complete -c agent-kit -n '__agent_kit_command_is search' -l count-matches
complete -c ak -n '__agent_kit_command_is search' -l count-matches
complete -c agent-kit -n '__agent_kit_command_is search' -l dry-run
complete -c ak -n '__agent_kit_command_is search' -l dry-run
complete -c agent-kit -n '__agent_kit_command_is search' -l exclude
complete -c ak -n '__agent_kit_command_is search' -l exclude
complete -c agent-kit -n '__agent_kit_command_is search' -l files-with-matches
complete -c ak -n '__agent_kit_command_is search' -l files-with-matches
complete -c agent-kit -n '__agent_kit_command_is search' -l fixed
complete -c ak -n '__agent_kit_command_is search' -l fixed
complete -c agent-kit -n '__agent_kit_command_is search' -l glob
complete -c ak -n '__agent_kit_command_is search' -l glob
complete -c agent-kit -n '__agent_kit_command_is search' -l help
complete -c ak -n '__agent_kit_command_is search' -l help
complete -c agent-kit -n '__agent_kit_command_is search' -l ignore-case
complete -c ak -n '__agent_kit_command_is search' -l ignore-case
complete -c agent-kit -n '__agent_kit_command_is search' -l lang
complete -c ak -n '__agent_kit_command_is search' -l lang
complete -c agent-kit -n '__agent_kit_command_is search' -l max-bytes
complete -c ak -n '__agent_kit_command_is search' -l max-bytes
complete -c agent-kit -n '__agent_kit_command_is search' -l max-depth
complete -c ak -n '__agent_kit_command_is search' -l max-depth
complete -c agent-kit -n '__agent_kit_command_is search' -l max-results
complete -c ak -n '__agent_kit_command_is search' -l max-results
complete -c agent-kit -n '__agent_kit_command_is search' -l messages
complete -c ak -n '__agent_kit_command_is search' -l messages
complete -c agent-kit -n '__agent_kit_command_is search' -l no-ignore
complete -c ak -n '__agent_kit_command_is search' -l no-ignore
complete -c agent-kit -n '__agent_kit_command_is search' -l no-ignore-dot
complete -c ak -n '__agent_kit_command_is search' -l no-ignore-dot
complete -c agent-kit -n '__agent_kit_command_is search' -l no-ignore-global
complete -c ak -n '__agent_kit_command_is search' -l no-ignore-global
complete -c agent-kit -n '__agent_kit_command_is search' -l no-ignore-parent
complete -c ak -n '__agent_kit_command_is search' -l no-ignore-parent
complete -c agent-kit -n '__agent_kit_command_is search' -l no-ignore-vcs
complete -c ak -n '__agent_kit_command_is search' -l no-ignore-vcs
complete -c agent-kit -n '__agent_kit_command_is search' -l patch
complete -c ak -n '__agent_kit_command_is search' -l patch
complete -c agent-kit -n '__agent_kit_command_is search' -l regex
complete -c ak -n '__agent_kit_command_is search' -l regex
complete -c agent-kit -n '__agent_kit_command_is search' -l smart-case
complete -c ak -n '__agent_kit_command_is search' -l smart-case
complete -c agent-kit -n '__agent_kit_command_is search' -l staged
complete -c ak -n '__agent_kit_command_is search' -l staged
complete -c agent-kit -n '__agent_kit_command_is search' -l type
complete -c ak -n '__agent_kit_command_is search' -l type
complete -c agent-kit -n '__agent_kit_command_is search' -s A
complete -c ak -n '__agent_kit_command_is search' -s A
complete -c agent-kit -n '__agent_kit_command_is search' -s B
complete -c ak -n '__agent_kit_command_is search' -s B
complete -c agent-kit -n '__agent_kit_command_is search' -s C
complete -c ak -n '__agent_kit_command_is search' -s C
complete -c agent-kit -n '__agent_kit_command_is search' -s h
complete -c ak -n '__agent_kit_command_is search' -s h
complete -c agent-kit -n '__agent_kit_command_is search' -s i
complete -c ak -n '__agent_kit_command_is search' -s i
complete -c agent-kit -n '__agent_kit_command_is search' -s l
complete -c ak -n '__agent_kit_command_is search' -s l

complete -c agent-kit -n '__agent_kit_needs_mode search-multi' -a 'changed-files changed-text class config config-key deps diff docs enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns'
complete -c ak -n '__agent_kit_needs_mode search-multi' -a 'changed-files changed-text class config config-key deps diff docs enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns'

complete -c agent-kit -n '__agent_kit_needs_mode session' -a 'checkpoint watch'
complete -c ak -n '__agent_kit_needs_mode session' -a 'checkpoint watch'

complete -c agent-kit -n '__agent_kit_command_is session-checkpoint' -l help
complete -c ak -n '__agent_kit_command_is session-checkpoint' -l help
complete -c agent-kit -n '__agent_kit_command_is session-checkpoint' -s h
complete -c ak -n '__agent_kit_command_is session-checkpoint' -s h

complete -c agent-kit -n '__agent_kit_needs_mode structured' -a 'csv json validate-json validate-yaml xml yaml'
complete -c ak -n '__agent_kit_needs_mode structured' -a 'csv json validate-json validate-yaml xml yaml'
complete -c agent-kit -n '__agent_kit_command_is structured' -l head
complete -c ak -n '__agent_kit_command_is structured' -l head
complete -c agent-kit -n '__agent_kit_command_is structured' -l help
complete -c ak -n '__agent_kit_command_is structured' -l help
complete -c agent-kit -n '__agent_kit_command_is structured' -s h
complete -c ak -n '__agent_kit_command_is structured' -s h

complete -c agent-kit -n '__agent_kit_needs_mode task' -a 'json lint list test typecheck verify'
complete -c ak -n '__agent_kit_needs_mode task' -a 'json lint list test typecheck verify'
complete -c agent-kit -n '__agent_kit_command_is task' -l help
complete -c ak -n '__agent_kit_command_is task' -l help
complete -c agent-kit -n '__agent_kit_command_is task' -s h
complete -c ak -n '__agent_kit_command_is task' -s h

complete -c agent-kit -n '__agent_kit_needs_mode test' -a 'all run select'
complete -c ak -n '__agent_kit_needs_mode test' -a 'all run select'
complete -c agent-kit -n '__agent_kit_command_is test' -l filter
complete -c ak -n '__agent_kit_command_is test' -l filter
complete -c agent-kit -n '__agent_kit_command_is test' -l help
complete -c ak -n '__agent_kit_command_is test' -l help
complete -c agent-kit -n '__agent_kit_command_is test' -l introspect
complete -c ak -n '__agent_kit_command_is test' -l introspect
complete -c agent-kit -n '__agent_kit_command_is test' -s h
complete -c ak -n '__agent_kit_command_is test' -s h

complete -c agent-kit -n '__agent_kit_needs_mode verify' -a 'docs refs'
complete -c ak -n '__agent_kit_needs_mode verify' -a 'docs refs'
complete -c agent-kit -n '__agent_kit_command_is verify' -l all
complete -c ak -n '__agent_kit_command_is verify' -l all
complete -c agent-kit -n '__agent_kit_command_is verify' -l check
complete -c ak -n '__agent_kit_command_is verify' -l check
complete -c agent-kit -n '__agent_kit_command_is verify' -l exclude
complete -c ak -n '__agent_kit_command_is verify' -l exclude
complete -c agent-kit -n '__agent_kit_command_is verify' -l ext
complete -c ak -n '__agent_kit_command_is verify' -l ext
complete -c agent-kit -n '__agent_kit_command_is verify' -l format
complete -c ak -n '__agent_kit_command_is verify' -l format
complete -c agent-kit -n '__agent_kit_command_is verify' -l help
complete -c ak -n '__agent_kit_command_is verify' -l help
complete -c agent-kit -n '__agent_kit_command_is verify' -l language
complete -c ak -n '__agent_kit_command_is verify' -l language
complete -c agent-kit -n '__agent_kit_command_is verify' -s h
complete -c ak -n '__agent_kit_command_is verify' -s h
