# agent-kit shell completion (bash) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

_agent_kit_completion()
{
    local current command
    current="${COMP_WORDS[COMP_CWORD]}"
    command="${COMP_WORDS[1]-}"
    COMPREPLY=()

    if ((COMP_CWORD == 1)); then
        mapfile -t COMPREPLY < <(compgen -W "all-f-into-one completion context doctor edit fd-files file-freshness git inspect preview-file refactor-scan repo repo-stats repo-tool-inventory rg-code rollback s search search-introspect search-multi session session-checkpoint structured task test verify watch-loop" -- "$current")
        return
    fi

    case "$command" in
        all-f-into-one)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        completion)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "auto bash fish zsh" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        context)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "diff ensure estimate file generate pack status tree" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--compress --help --multiplier --multiplier-label --no-compress --no-regen --output --regen --reserved-output --style -h --help --introspect" -- "$current")
            fi
            ;;

        doctor)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        edit)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "apply ast-grep comby patch rollback sd" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--allow-dirty-tree --apply --dry-run --exclude --format --glob --help --max-bytes --max-files --max-replacements --no-verify --require-clean-tree --verify -h --help --introspect" -- "$current")
            fi
            ;;

        fd-files)
            mapfile -t COMPREPLY < <(compgen -W "--help --hidden --json --type -h --help --introspect" -- "$current")
            ;;

        file-freshness)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        git)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "blame history origin pr-context" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--checks --diff --field --help --json --pack --reviews -h --help --introspect" -- "$current")
            fi
            ;;

        inspect)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "data file shell" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        preview-file)
            mapfile -t COMPREPLY < <(compgen -W "--around --context --dry-run --force --help --lines --max-bytes --max-columns --plain --range -h --help --introspect" -- "$current")
            ;;

        refactor-scan)
            mapfile -t COMPREPLY < <(compgen -W "--ccn-threshold --complexity-threshold --exclude-dir --ext --fail-on-findings --folder --help --human --lang --nloc-threshold --no-parallel --no-report --output-dir --param-threshold --quiet --scc-format -h --help --introspect" -- "$current")
            ;;

        repo)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "stats status tasks tools" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        repo-stats)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        repo-tool-inventory)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        rg-code)
            mapfile -t COMPREPLY < <(compgen -W "--context --count --files --help --ignore-case --json --mode --type -C -h -i --help --introspect" -- "$current")
            ;;

        rollback)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "apply list prune show" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--days --help -h --help --introspect" -- "$current")
            fi
            ;;

        s)
            mapfile -t COMPREPLY < <(compgen -W "--changed --config --deps --diff --docs --history --staged --tests --tracked --help --introspect" -- "$current")
            ;;

        search)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "batch capabilities changed-files changed-text class config config-key deps diff docs doctor enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--absolute --after-context --base --before-context --case-sensitive --context --count --count-matches --dry-run --exclude --files-with-matches --fixed --glob --help --ignore-case --lang --max-bytes --max-depth --max-results --messages --no-ignore --no-ignore-dot --no-ignore-global --no-ignore-parent --no-ignore-vcs --patch --regex --smart-case --staged --type -A -B -C -h -i -l --help --introspect" -- "$current")
            fi
            ;;

        search-introspect)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

        search-multi)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "changed-files changed-text class config config-key deps diff docs enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        session)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "checkpoint watch" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        session-checkpoint)
            mapfile -t COMPREPLY < <(compgen -W "--help -h --help --introspect" -- "$current")
            ;;

        structured)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "csv json validate-json validate-yaml xml yaml" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--head --help -h --help --introspect" -- "$current")
            fi
            ;;

        task)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "json lint list test typecheck verify" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--help -h --help --introspect" -- "$current")
            fi
            ;;

        test)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "all run select" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--filter --help --introspect -h --help --introspect" -- "$current")
            fi
            ;;

        verify)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "docs refs" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--all --check --exclude --ext --format --help --language -h --help --introspect" -- "$current")
            fi
            ;;

        watch-loop)
            mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            ;;

    esac
}

complete -o bashdefault -o default -F _agent_kit_completion agent-kit ak
