# restsift shell completion (bash) — generated by scripts/gen-completions.sh
# from libexec/internal/completion-spec. Do not edit by hand.

_restsift_completion()
{
    local current command
    current="${COMP_WORDS[COMP_CWORD]}"
    command="${COMP_WORDS[1]-}"
    COMPREPLY=()

    if ((COMP_CWORD == 1)); then
        mapfile -t COMPREPLY < <(compgen -W "all-f-into-one bundle ckpt comp completion context ctx data doctor e edit fd fd-files file-freshness fresh g git i inspect peek preview-file rb refactor refactor-scan repo repo-stats repo-tool-inventory repomix-profile-lab rg rg-code rollback s search search-introspect search-multi session session-checkpoint si sm stats structured t task test tools tsk v verify w watch-loop" -- "$current")
        return
    fi

    case "$command" in
        all-f-into-one|bundle)
            mapfile -t COMPREPLY < <(compgen -W "--json --help --introspect" -- "$current")
            ;;

        completion|comp)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "auto bash fish zsh" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        context|ctx)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "diff ensure estimate file generate pack status tree" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--compress --help --multiplier --multiplier-label --no-compress --no-regen --output --regen --reserved-output --style -h --help --introspect" -- "$current")
            fi
            ;;

        doctor)
            mapfile -t COMPREPLY < <(compgen -W "--help --introspect --json -h --help --introspect" -- "$current")
            ;;

        edit|e)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "apply ast-grep comby patch rollback sd" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--allow-dirty-tree --apply --dry-run --exclude --format --glob --help --max-bytes --max-files --max-replacements --no-verify --require-clean-tree --verify -h --help --introspect" -- "$current")
            fi
            ;;

        fd-files|fd)
            mapfile -t COMPREPLY < <(compgen -W "--help --hidden --json --type -h --help --introspect" -- "$current")
            ;;

        file-freshness|fresh)
            mapfile -t COMPREPLY < <(compgen -W "--exit-code --json --help --introspect" -- "$current")
            ;;

        git|g)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "blame conflicts files history origin pr-context" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--checks --conflicts --diff --fail-on-findings --field --help --json --name-only --pack --reviews -h --help --introspect" -- "$current")
            fi
            ;;

        inspect|i)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "data file shell" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        preview-file|peek)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "around dry-run lines range" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--around --context --dry-run --force --help --lines --max-bytes --max-columns --plain --range -h --help --introspect" -- "$current")
            fi
            ;;

        refactor-scan|refactor)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "all comments complexity dupes nloc" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--all --ccn-threshold --changed --complexity-threshold --exclude-dir --ext --fail-on-error --fail-on-findings --files-from --folder --help --human --lang --markers --max-depth --nloc-threshold --no-parallel --no-report --output-dir --param-threshold --quiet --report-format --scc-format --strict --token-threshold -h --help --introspect" -- "$current")
            fi
            ;;

        repo)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "stats status tasks tools" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--introspect --help --introspect" -- "$current")
            fi
            ;;

        repo-stats|stats)
            mapfile -t COMPREPLY < <(compgen -W "--json --help --introspect" -- "$current")
            ;;

        repo-tool-inventory|tools)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "json table" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--help --introspect --json --help --introspect" -- "$current")
            fi
            ;;

        repomix-profile-lab)
            mapfile -t COMPREPLY < <(compgen -W "--budget --json --style --help --introspect" -- "$current")
            ;;

        rg-code|rg)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "all blade config default js kotlin php tracked" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--context --count --files --help --ignore-case --json --mode --type -C -h -i --help --introspect" -- "$current")
            fi
            ;;

        rollback|rb)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "apply list prune show" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--days --help --json -h --help --introspect" -- "$current")
            fi
            ;;

        s)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "changed-text config deps diff docs history staged-text tests text tracked" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--changed --config --deps --diff --docs --history --staged --tests --tracked --help --introspect" -- "$current")
            fi
            ;;

        search)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "batch capabilities changed-files changed-text class config config-key deps diff docs doctor enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--absolute --after-context --base --before-context --case-sensitive --context --count --count-matches --dry-run --exclude --files-with-matches --fixed --glob --help --ignore-case --introspect --lang --max-bytes --max-depth --max-results --messages --no-ignore --no-ignore-dot --no-ignore-global --no-ignore-parent --no-ignore-vcs --patch --pcre2 --regex --smart-case --staged --type -A -B -C -h -i -l --help --introspect" -- "$current")
            fi
            ;;

        search-introspect|si)
            mapfile -t COMPREPLY < <(compgen -W "--help --introspect --json --probe --help --introspect" -- "$current")
            ;;

        search-multi|sm)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "changed-files changed-text class config config-key deps diff docs enum files function history interface method route staged-files staged-text struct symbols tests text todo tracked unsafe-patterns" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W " --help --introspect" -- "$current")
            fi
            ;;

        session)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "checkpoint watch" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--introspect --help --introspect" -- "$current")
            fi
            ;;

        session-checkpoint|ckpt)
            mapfile -t COMPREPLY < <(compgen -W "--json --help --introspect" -- "$current")
            ;;

        structured|data)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "csv json validate-json validate-yaml xml yaml" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--head --help -h --help --introspect" -- "$current")
            fi
            ;;

        task|tsk)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "json lint list test todos typecheck verify" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--json --pending -p --help --introspect" -- "$current")
            fi
            ;;

        test|t)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "all run select" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--filter --help --introspect -h --help --introspect" -- "$current")
            fi
            ;;

        verify|v)
            if ((COMP_CWORD == 2)); then
                mapfile -t COMPREPLY < <(compgen -W "docs refs" -- "$current")
            else
                mapfile -t COMPREPLY < <(compgen -W "--all --check --exclude --ext --format --help --json --language -h --help --introspect" -- "$current")
            fi
            ;;

        watch-loop|w)
            mapfile -t COMPREPLY < <(compgen -W "--json --help --introspect" -- "$current")
            ;;

    esac
}

complete -o bashdefault -o default -F _restsift_completion restsift res agent-kit ak
